name: Publish Server Docker

on:
  push:
    branches:
      - master

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Run Tests
      run: ./test.sh
      working-directory: tunshell-server
      shell: bash
      env:
        RUST_LOG: debug

    - name: Publish to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: timetoogo/tunshell-relay
        dockerfile: tunshell-server/docker/prod.Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest"